[package]
name = "solfort"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-sdk = "1.17"
solana-client = "1.17"
solana-clap-utils = "1.17"
clap = { version = "4.4", features = ["derive"] }
anyhow = "1.0"